### ISSUE TITLE
Daten mit ins Binary schreiben

### ISSUE THREAD

**Issue by gruselhaus** [Parteiduell/backend#5]
@redsolver Hi, weißt du, ob man die Quizdaten direkt mit ins Binary schreiben kann?

**Comment by redsolver** [comment]
Ja, ist möglich

**Comment by redsolver** [comment]
Ist aber mMn eher weniger sinnvoll, da man die Daten dann schwerer austauschen kann

**Comment by gruselhaus** [comment]
Könnte man das irgendwie über ein Argument an den Dart-Compiler steuern?

**Comment by redsolver** [comment]
Der beste Ansatz, der mir dafür einfällt, wäre eine `data.dart`-Datei vor dem Kompilierprozess zu erstellen, da JSON auch gültiger Dart-Code ist. An welcher Stelle im CI stellst du dir das Einbinden der Daten vor und von wo?

**Comment by gruselhaus** [comment]
Aktuell übertrage ich ja die Binary + Daten mit `rsync` an den Server. Wenn wir die Daten aber ins Binary schreiben würden, würde es mir serverseitig einiges an hin und herschieberei sparen ....
```yaml
name: Build Test & Deploy
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - name: "Fetching ParteiDuell Data"
        uses: textbook/git-checkout-submodule-action@master
      - name: Install dependencies
        run: pub get
      - name: Building source
        run: dart2native bin/main.dart -o parteiduell_backend-linux-x64-release
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: parteiduell_backend-linux-x64-release
  deploy:
    name: Deploy to production
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Fetching ParteiDuell Data"
        uses: textbook/git-checkout-submodule-action@master      
      - name: Download build artifact
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Deploy build
        env:
          SSH_HOST_KEY: ${{secrets.SSH_HOST_KEY}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          echo "$SSH_HOST_KEY" > ~/.ssh/known_hosts
          rsync -az --progress -e ssh ./build/parteiduell_backend-linux-x64-release data root@parteiduell.de:/var/www/api.parteiduell.de/production/build --delete
      - name: Restart the backend service on the server
        run: |
          ssh root@parteiduell.de chmod a+x /var/www/api.parteiduell.de/production/build/parteiduell_backend-linux-x64-release
          ssh root@parteiduell.de sudo systemctl restart parteiduell_backend
```
